### ISSUE TITLE
Inconsistent naming of parameters in Snakefile and parameters.yaml

### ISSUE THREAD

**Issue by katkopera** [MetaSUB-CAMP/camp_short-read-quality-control#5]
I've noticed inconsistency in parameter naming between Snakefile and parameters.yaml

In rule filter_adapters:
params:
        trim_exec = config['trim_exec'],
        trim_adapters = config['adapters'],
        minqual = config['minqual'],

Snakefile expects 'trimmomatic_exec' while in parameters.yaml there is 'trim_exec'.
Snakefile expects 'adapters' while in parameters.yaml there is 'trim_adapters'.

This leads to KeyErrors. Please fix.

**Comment by tommyfuu** [comment]
hi,

Sorry about that - that was due to a previous commit not consistent with the rest of the repo.

It should now be fixed - check out `config/parameters.yaml` for the file. If you want an example of these file paths, check out `test_data/parameters.yaml`.

Let me know if you have any more questions.

**Comment by lauren-mak** [comment]
This has been addressed in the latest update (version 0.7.0). Please pull it, go over the `README.md` to make sure the module has been set up properly, and see if it works. Thanks for using the CAMP short-read QC module!
