### ISSUE TITLE
Found conflicts with setting up the conda environment from yaml files 

### ISSUE THREAD

**Issue by yuvaramsingh94** [MetaSUB-CAMP/camp_short-read-quality-control#7]
Hi,
while setting up the conda environment through snakemake (env : multiq) i am facing dependency conflicts issue. the strict pkg versions mentioned in the `multiqc.yaml` file is causing the issue. is there a workaround for this.  does installing pkg without specifying the version advisable?

linux : centos
conda : 4.12.0

some of the conflicts

```
Package kiwisolver conflicts for:
kiwisolver==1.3.1=py36h605e78d_1
multiqc==1.13=pyhdfd78af_0 -> matplotlib-base[version='>=2.1.1'] -> kiwisolver[version='>=1.0.1']
matplotlib-base==3.3.4=py36hd391965_0 -> kiwisolver[version='>=1.0.1']

Package rich conflicts for:
rich==12.5.1=pyhd8ed1ab_0
rich-click==1.3.0=pyhd8ed1ab_0 -> rich[version='>=10']
multiqc==1.13=pyhdfd78af_0 -> rich-click -> rich[version='>=10,<12']
multiqc==1.13=pyhdfd78af_0 -> rich[version='>=10']

```

Thanks
yuvaram

**Comment by b-tierney** [comment]
@tommyfuu did you face this on your recent test?

**Comment by tommyfuu** [comment]
hey! while i did not face this particular conflict in my own testing, i would recommend two things

(1) in case you last pulled from the repo before I last updated it, trying pulling again and get the most updated yaml file
(2) change the version of the rick package in your multiqc.yaml to `10.x.x` or `11.x.x` to resolve the conflict with other packages. while i am not exactly sure why kiwisolver is giving conflict because it looks like the version it's trying to install (1.3.1) is indeed newer than 1.0.1 that the other packages requires, my guess is that multiqc/matplotlib actually inherently requires even newer version of it without writing it into dependency requirement. For that you can replace `1.3.1` with some newer version as well.

also, make sure you use mamba instead of conda to speed up!

Eventually we will have these yaml files all cleaned up and only with the necessary versioning requirements.

Let me know if that helps!

**Comment by yuvaramsingh94** [comment]
Thanks @b-tierney @tommyfuu . i am using the most updated yaml file. i am still getting the dependency conflicts. its nice to know that in future we will have version requirement only for necessary pkgs. 
is there any plan to have a built docker image for the same?

**Comment by lauren-mak** [comment]
We're looking at one potential Docker-based idea for a centralized CAMP, but it won't be available in the near future. Are you still experiencing issues with installing MultiQC?
